name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: "${{ secrets.FTP_HOST }}"
          username: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          exclude: |
            **/.git*
            **/.git*/**
            .gitpod.yml
            README.md
          server-dir: "${{ secrets.FTP_DIR }}"
          log-level: standard
