name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: "${{ secrets.FTP_HOST }}"
          username: "${{ secrets.FTP_USERNAME }}"
          password: "${{ secrets.FTP_PASSWORD }}"
          exclude: "[**/.git*, **/.git*/**, .gitpod.yml]"
          server-dir: "${{ secrets.FTP_DIR }}"
          log-level: standard
